### ISSUE TITLE
Samtools and sambamba in QC lesson

### ISSUE THREAD

**Issue by mistrm82** [hbctraining/Intro-to-ChIPseq#34]
- Samtools is being used in QC lesson, needs more detail to introduce it. 
- Add a note on similarities between samtools and sambamba. Only using sambamba where necessary.

**Comment by rkhetani** [comment]
Decided to leave in both Samtools and sambamba at this time. Leaving this issue open though.

**Comment by mistrm82** [comment]
I think we can close it if samtools cannot do the filtering that sambamba can, we won't change it

**Comment by rkhetani** [comment]
Okay, closing it.
