### ISSUE TITLE
Poisson's pmf

### ISSUE THREAD

**Issue by hreypar** [hbctraining/Intro-to-ChIPseq#61]
Hi, is the probability mass function of Poisson's distribution correct in the [Peak detection](https://github.com/hbctraining/Intro-to-ChIPseq/blob/master/lessons/05_peak_calling_macs.md#peak-detection) section?

**Comment by mistrm82** [comment]
Hi @hreypar I am not entirely sure what you are asking. Do you mind elaborating on your question? Thanks!
