### ISSUE TITLE
diffbind DE peak results different to DESeq2 or edgeR results by myself

### ISSUE THREAD

**Issue by yx-xu** [hbctraining/Intro-to-ChIPseq#67]
Hi!
     i use diffbind's DESeq2/edgeR to call DE peak , and directly use DESeq2/edgeR by myself, but their results are different; diffbind's results are more; and their threshold all are |LFC| > 1 && FDR < 0.05; which results should i trust?

Thanks for your help!

**Comment by mistrm82** [comment]
Hi, there will be differences depending on what you select for your normalization methods in DiffBind. The defaults are not the same as what is implemented in DESeq2 or edgeR. We recommend posting this question to the Bioconductor support site as the DiffBind developers can help better address this.

Also, please note that this repo is not currently maintained. For our more recent ChIP-seq materials use this repo: https://github.com/hbctraining/Intro-to-ChIPseq-flipped/tree/main/schedule
