### ISSUE TITLE
Visualization of peaks-about the bed file

### ISSUE THREAD

**Issue by wisRen** [hbctraining/Intro-to-ChIPseq#70]
Where can I find the bed file？https://hbctraining.github.io/Intro-to-ChIPseq/lessons/10_data_visualization.html

**Comment by mistrm82** [comment]
Hi, we currently do not have links to the data used in the workshop. Please note that this repo is not currently maintained. For our more recent ChIP-seq materials see here: https://github.com/hbctraining/Intro-to-ChIPseq-flipped/tree/main/schedule
