### ISSUE TITLE
macs2 bdgpeakcall only gives a few peaks

### ISSUE THREAD

**Issue by jiangshan529** [hbctraining/Intro-to-ChIPseq#71]
Hi, all. I want to call peaks from bigwig file. I first transfer bigwig to bedgraph by using "bigWigToBedGraph A.bw A.bedgraph", then I use "macs2 bdgpeakcall -i A.bedgraph -o A" to call peaks from bedgraph. However, there are only a few peaks(8 peaks) shown up. I am pretty sure there are many peaks by viewing the bigwig file in IGV. Does anybody have a good idea about why this happens? Thanks!

**Comment by mistrm82** [comment]
Hi @jiangshan529, we don't have a lot of experience using macs2 bdgpeakcall. We recommend posting this issue the macs2 Github repo as they will be able to help you better.
